# Generated by Django 2.1.9 on 2019-07-03 11:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eetlijst', '0009_datelist_eta_time'),
    ]

    def couple_dinner_userentries(apps, schema_editor):
        UserDinner = apps.get_model('eetlijst', 'UserDinner')
        Dinner = apps.get_model('eetlijst', 'Dinner')
        for user_dinner in UserDinner.objects.all():
            try:
                dinner = Dinner.objects.get(date=user_dinner.list_date)
                user_dinner.dinner = dinner
                user_dinner.save()
            except Exception as e:
                print("Couldnt get a date for this userdinner entry.", str(e))

    operations = [
        migrations.RenameModel(
            old_name='DateList',
            new_name='Dinner',
        ),
        migrations.RenameModel(
            old_name='UserList',
            new_name='UserDinner',
        ),
        migrations.AddField(
            model_name='UserDinner',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eetlijst.Dinner', null=True),
        ),
        migrations.RunPython(couple_dinner_userentries)
    ]
